import DekFile from './DekFile.tsx';

function DekFileExamples(): DekFile[] {

  return [
    new DekFile(0, 'Mining Truck', '', '',),
    new DekFile(1, 'Auto Turret', '', '',),
    new DekFile(2, 'Anti-Armor Pod', '', '',),
    new DekFile(3, 'Assault Troopers', '', '',),
    new DekFile(5,  'Decon ATV', '', '',),
    new DekFile(6,  'Crusader ATV', '', '',),
    new DekFile(7,  'Shepard Tank', '', '',),
    new DekFile(8,  'SAM Tank', '', '',),
    new DekFile(9,  'Spitfire Chopper', '', '',),
    new DekFile(10, 'Seraphim', '', '',),
    new DekFile(11, 'Ghosts', '', '',),
    new DekFile(12, 'Brimstone Artillery', '', '',),
    new DekFile(13, 'Enabler', '', '',),
    new DekFile(14, 'Pulsar Tower', '', '',),
    new DekFile(15, 'Anti-Air Platform', '', '',),
    new DekFile(16, 'Sentinel', '', '',),
    new DekFile(17, 'Sentry Bots', '', '',),
    new DekFile(18, 'Wheel Drones', '', '',),
    new DekFile(19, 'Keeper Tank', '', '',),
    new DekFile(20, 'Pulsar Tank', '', '',),
    new DekFile(21, 'Synergizer', '', '',),
    new DekFile(22, 'Strafer Jet', '', '',),
    new DekFile(23, 'Amplifier', '', '',),
    new DekFile(24, 'Hunter Probe', '', '',),
    new DekFile(25, 'Pulsar Cruiser', '', '',),
    new DekFile(26, 'Heavy Destroyer', '', '',),
    new DekFile(27, 'Phage', '', '',),
    new DekFile(28, 'Tendril Pod', '', '',),
    new DekFile(29, 'Reaper Spine', '', '',),
    new DekFile(30, 'Swarmenvash', '', '',),
    new DekFile(31, 'Scraper', '', '',),
    new DekFile(32, 'Tormenvash', '', '',),
    new DekFile(33, 'Glutton', '', '',),
    new DekFile(34, 'Necrovash', '', '',),
    new DekFile(35, 'Harbinger', '', '',),
    new DekFile(36, 'Screechers', '', '',),
    new DekFile(37, 'Blight Spitter', '', '',),
    new DekFile(38, 'Spawn Pit', '', '',),
    new DekFile(39, 'Nestlings', '', '',),
    new DekFile(40, 'Slayer', '', '',),
    new DekFile(41, 'Swarm Queen', '', '',),
    new DekFile(42, 'Shadow Hive', '', '',),
    new DekFile(43, 'Hiveling', '', '',),
    new DekFile(44, 'Titanipede', '', '',),
  ];
}

export default DekFileExamples;